addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '8'
before_install:
  - npm i -g npm@^5.0.0  
before_script:
  - npm prune
script: 
 - npm run test:unit 
 - npm run webdriver-manager:update
 - npm run test:local -- --browserName chrome-headless 
after_success:
  - npm run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
